// Modified from copy found in devtools
export const CAMP_NAMES = {
  BDPW: 'Baylor',
  CNDI: 'Berkeley',
  BDL: 'Boston Debate League',
  CDL: 'Chicago Debate League',
  DDI: 'Dartmouth DDI',
  DDIx: 'Dartmouth DDIx',
  ENDI: 'Emory',
  GDS: 'Georgetown',
  UGA: 'Georgia',
  GMDI: 'George Mason',
  GDI: 'Gonzaga',
  HDC: 'Harvard',
  HSS: 'Hoya-Spartan Scholars',
  JDI: 'Kansa',
  MGC: 'Mean Green Comet',
  UM7: 'Michigan 7-week',
  UMC: 'Michigan Classic',
  MNDI: 'Michigan',
  SDI: 'Michigan State',
  MSDI: 'Missouri State',
  MGF: 'MoneyGram Foundation',
  NSD: 'National Symposium for Debate',
  NAUDL: 'NAUDL',
  NDI: 'Nebraska',
  NHSI: 'Northwestern',
  SSDI: 'Samford',
  SCDI: 'Sun Country',
  UMKC: 'UMKC',
  UTNIF: 'Texas',
  UNT: 'North Texas',
  UTD: 'UT Dallas',
  TDI: 'The Debate Intensive',
  RKS: 'Wake Forest',
  WSDI: 'Weber State',
  WYO: 'Wyoming',
} as const;

export const OPENEV_TYPES = {
  aff: 'Affirmatives',
  neg: 'Case Negatives',
  cp: 'Counterplans',
  atcp: 'Counterplan Answers',
  da: 'Disadvantages',
  atda: 'Disadvantage Answers',
  impact: 'Impact Files',
  atk: 'Kritik Answers',
  k: 'Kritiks',
  ld: 'Lincoln Douglas',
  pol: 'Politics',
  pf: 'Public Forum',
  th: 'Theory',
  t: 'Topicality',
  f: 'Framework',
} as const;

export const EVENT_NAMES = {
  cx: 'Policy',
  ld: 'Lincoln Douglas',
  pf: 'Public Forum',
};
