/**
 * Caselist API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Caselist {
    'caselistId'?: number;
    'slug'?: string;
    'name'?: string;
    'event'?: string;
    'year'?: number;
    'archived'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "caselistId",
            "baseName": "caselist_id",
            "type": "number"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "string"
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Caselist.attributeTypeMap;
    }
}

