/**
 * Caselist API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Caselist {
    'caselistId': number;
    'name': string;
    'displayName': string;
    'year': number;
    'event': string;
    'level': string;
    'teamSize': number;
    'archived': boolean;
    'archiveUrl'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "caselistId",
            "baseName": "caselist_id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string"
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "string"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "string"
        },
        {
            "name": "teamSize",
            "baseName": "team_size",
            "type": "number"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "archiveUrl",
            "baseName": "archive_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Caselist.attributeTypeMap;
    }
}

