/**
 * Caselist API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ModelFile {
    'openevId'?: number;
    'name'?: string;
    'path'?: string;
    'year'?: number;
    'camp'?: string;
    'lab'?: string;
    'tags'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "openevId",
            "baseName": "openev_id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "camp",
            "baseName": "camp",
            "type": "string"
        },
        {
            "name": "lab",
            "baseName": "lab",
            "type": "string"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return ModelFile.attributeTypeMap;
    }
}

