/**
 * Caselist API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class School {
    'schoolId': number;
    'caselistId': number;
    'name': string;
    'displayName': string;
    'state'?: string | null;
    'chapterId'?: number;
    'archived': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "schoolId",
            "baseName": "school_id",
            "type": "number"
        },
        {
            "name": "caselistId",
            "baseName": "caselist_id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "display_name",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "chapterId",
            "baseName": "chapter_id",
            "type": "number"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return School.attributeTypeMap;
    }
}

