/**
 * Caselist API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TabroomRound {
    'id'?: number;
    'tournament'?: string;
    'round'?: string;
    'side'?: string;
    'opponent'?: string;
    'judge'?: string;
    'startTime'?: string;
    'share'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "tournament",
            "baseName": "tournament",
            "type": "string"
        },
        {
            "name": "round",
            "baseName": "round",
            "type": "string"
        },
        {
            "name": "side",
            "baseName": "side",
            "type": "string"
        },
        {
            "name": "opponent",
            "baseName": "opponent",
            "type": "string"
        },
        {
            "name": "judge",
            "baseName": "judge",
            "type": "string"
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "string"
        },
        {
            "name": "share",
            "baseName": "share",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TabroomRound.attributeTypeMap;
    }
}

